#!/usr/bin/with-contenv bash

# Активировать виртуальное окружение
source /usr/src/app/venv/bin/activate

# Прочитать параметры из options.json
MQTT_BROKER=$(bashio::config 'mqtt_broker')
MQTT_PORT=$(bashio::config 'mqtt_port')
MQTT_USERNAME=$(bashio::config 'mqtt_username')
MQTT_PASSWORD=$(bashio::config 'mqtt_password')
SERIAL_PORT=$(bashio::config 'serial_port')

export MQTT_BROKER MQTT_PORT MQTT_USERNAME MQTT_PASSWORD SERIAL_PORT

# Запуск основного Python-скрипта как PID=1
exec python3 /usr/src/app/ghp-mm2mqtt.py
