#!/usr/bin/with-contenv bash

source /usr/src/app/venv/bin/activate

MQTT_BROKER=$(bashio::config 'mqtt_broker')
MQTT_PORT=$(bashio::config 'mqtt_port')
MQTT_USERNAME=$(bashio::config 'mqtt_username')
MQTT_PASSWORD=$(bashio::config 'mqtt_password')
SERIAL_PORT=$(bashio::config 'serial_port')

export MQTT_BROKER MQTT_PORT MQTT_USERNAME MQTT_PASSWORD SERIAL_PORT

exec python3 /usr/src/app/ghp-mm2mqtt.py
